name: Tests (uv)

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  test-uv:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        python-version: ['3.13']

    steps:
      - uses: actions/checkout@v5

      # might need to replace this with pipx install uv
      #- name: Install the latest version of uv
      #  uses: astral-sh/setup-uv@v6
      #  with:
      #    enable-cache: true
      #    activate-environment: true
      #    python-version: ${{ matrix.python-version }}

      - name: Install uv
        run: pipx install uv

      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Install cookiecutter and pytest dependencies
        run: pip install -r dev-requirements.txt

      - name: Run unit tests
        run: pytest

      - name: Create project from template
        # Choose default options
        run: cookiecutter . --no-input packaging=uv rse_team_as_coauthor=true use_bsd3_license=true

      - name: Install project dependencies
        working-directory: my_project
        run: uv sync --all-groups

      - name: Install pre-commit hooks
        working-directory: my_project
        run: uv run pre-commit install

      - name: Run mypy
        working-directory: my_project
        run: uv run mypy .

      - name: Run tests
        working-directory: my_project
        run: uv run pytest

      - name: Run pre-commit hooks for project
        working-directory: my_project
        run: |
          git init
          git add .
          uv run pre-commit run -all-files

      - name: Test docs build successfully
        working-directory: my_project
        run: uv run mkdocs build --strict

      - name: Test build is successful
        working-directory: my_project
        run: |
          uv build
